/**
 * Zod schemas for template input validation.
 *
 * These schemas are the contract between the UI forms/Server Actions and the
 * underlying data layer. All template mutation inputs are validated here
 * before reaching the database.
 *
 * Security: workspaceId never comes from client payload — it is derived from
 * the server session and validated against membership (D-12, T-03-01-03).
 * The schema JSON column is always derived server-side from parse(markup) —
 * it is never accepted from the client.
 *
 * Per D-06: required (boolean) is the only field-level validation beyond type
 * in v1; no regex or range validators are defined here.
 */
import { z } from "zod";

// -----------------------------------------------------------------------
// Shared field — metadataOverlay
// -----------------------------------------------------------------------

const MetadataOverlaySchema = z
  .record(
    z.string(),
    z.object({
      label: z.string(),
      required: z.boolean(),
    })
  )
  .optional();

// -----------------------------------------------------------------------
// CreateTemplateSchema
// -----------------------------------------------------------------------

export const CreateTemplateSchema = z.object({
  /** Human-readable template name, 1-128 characters. */
  name: z
    .string()
    .min(1, "Template name is required")
    .max(128, "Template name must be 128 characters or less")
    .trim(),

  /**
   * The raw markup string containing Liquid template syntax with token placeholders.
   * The engine's parse() will be run server-side to derive the schema.
   */
  markup: z.string().min(1, "Markup is required"),

  /**
   * Optional initial metadata overlay.
   * Keyed by field name, each entry carries label (string) and required (boolean).
   * If not provided, defaults are generated by reconcileMetadataOverlay.
   */
  metadataOverlay: MetadataOverlaySchema,
});

export type CreateTemplateInput = z.infer<typeof CreateTemplateSchema>;

// -----------------------------------------------------------------------
// UpdateTemplateSchema
// -----------------------------------------------------------------------

export const UpdateTemplateSchema = z.object({
  /** Required: the template ID to update. */
  id: z.string().cuid("Invalid template ID"),

  /** New human-readable name (optional on update). */
  name: z
    .string()
    .min(1, "Template name is required")
    .max(128, "Template name must be 128 characters or less")
    .trim()
    .optional(),

  /** New markup content (optional on update). When provided, schema is re-derived server-side. */
  markup: z.string().min(1, "Markup is required").optional(),

  /** Updated metadata overlay (optional on update). */
  metadataOverlay: MetadataOverlaySchema,
});

export type UpdateTemplateInput = z.infer<typeof UpdateTemplateSchema>;
